<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


defined('BASEPATH') OR exit('No direct script access allowed');

require_once(APPROOT . "/bootstrap.php");

use orm\User;
use orm\Session;

/**
 * Description of Auth
 *
 * @author olga
 */
class Auth extends REST_Controller 
{
	/**
	 *
	 * @var DoctrineORM
	 */
	private $doctrine;
	
	public function __construct() {
		parent::__construct();
		$this->doctrine = new DoctrineORM();
	}
	
	public function index_get()
	{
		$orm = $this->doctrine->getORM();
		
		$user = $orm
				->getRepository('orm\User')
				->findOneBy(['login' => 'test']);
		
		if ($user) {
			echo "deleting";
			$orm->remove($user);
			$orm->flush();
		}
		
		$user = new User();
		$user->setLogin("test");
		$user->setPassword("123456");
		
		$session = new Session();
		$session->setCreated(new DateTime('now'));
		$session->setToken("qwe");
		$session->setUser($user);
		
		$orm->persist($user);
		$orm->persist($session);
		$orm->flush();
		
		$user = $orm
				->getRepository('orm\User')
				->findOneBy(['login' => 'test']);

		echo "Password " . $user->getPassword() . "\n";
		//print_r($this->dbHelper);
		//echo $this->config->item('username', 'database'); 
	}
	
	public function index_post()
    {
		//error_log($_REQUEST);
		$user = $this->post('username');
		$password = $this->post('password');
		
        // $this->some_model->update_user( ... );
        $message = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('username'),
            'password' => $this->post('password'),
            'message' => 'Added a resource'
        ];
		
        header("Access-Control-Allow-Origin: *");
		
		$this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
}
