<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


defined('BASEPATH') OR exit('No direct script access allowed');

require_once(APPROOT . "/bootstrap.php");

use orm\User;

/**
 * Description of Auth
 *
 * @author olga
 */
class Auth extends REST_Controller 
{
	private $orm;
	
	public function __construct() {
		parent::__construct();
		$db = new DoctrineORM();
		$this->orm = $db->getORM();
	}
	
	public function index_get()
	{
		$user = new User();
		$user->setName("test2");
		$user->setPassword("123456");
		
		$this->orm->persist($user);
		$this->orm->flush();

		echo "Created user with ID " . $user->getId() . "\n";
		//print_r($this->dbHelper);
		//echo $this->config->item('username', 'database'); 
	}
	
	public function index_post()
    {
		//error_log($_REQUEST);
		$user = $this->post('username');
		$password = $this->post('password');
		
        // $this->some_model->update_user( ... );
        $message = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('username'),
            'password' => $this->post('password'),
            'message' => 'Added a resource'
        ];
		
        header("Access-Control-Allow-Origin: *");
		
		$this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
}
